feat(svg): update crown logo and add missing favicon
dvsa/olcs-maintenance-page pull request #1
Opened 2024-02-19 16:15 UTC by sanakhandvsa

## Description

Ticket : [VOL-4960](https://dvsa.atlassian.net/browse/VOL-4960)

update crown logo and add missing favicon

Related issue: [JIRA_TICKET_NUMBER](LINK_TO_JIRA_TICKET)

## Before submitting (or marking as "ready for review")

- [x] Does the pull request title follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification?
- [x] Have you performed a self-review of the code
- [ ] Have you have added tests that prove the fix or feature is effective and working
- [ ] Did you make sure to update any documentation relating to this change?

2024-02-19 16:43 UTC, JoshuaLicense requested changes

2024-02-19 16:43 UTC, JoshuaLicense commented on index.html
> +    <link rel="shortcut icon" sizes="16x16 32x32 48x48" href="/assets/images/favicon.ico" type="image/x-icon">
The `favicon.ico` that is part of the PR does not have `16x16` & `32x32` size, does it?

2024-02-19 16:44 UTC, JoshuaLicense commented
Please add ticket number to the PR description please @sanakhandvsa

2024-02-20 14:32 UTC, sanakhandvsa commented on index.html
> +    <link rel="shortcut icon" sizes="16x16 32x32 48x48" href="/assets/images/favicon.ico" type="image/x-icon">
I noticed that in our repositories (`olcs-selfserve` and`olcs-internal`), we have different favicon sizes specified in the HTML as well. That's why I copied over same in `maintenence-page`

However, according to the [GOV.UK_Frontend v](https://github.com/alphagov/govuk-frontend/releases/tag/v4.8.0) 4.8.0 repo, only one 16x16 favicon is provided.  

To maintain consistency across our projects, what do you think about updating the favicon across all repositories to match the guidelines provided by GOV.UK_Frontend v4.8.0 or just remove on this repo?

2024-02-20 14:45 UTC, JoshuaLicense commented on index.html
> +    <link rel="shortcut icon" sizes="16x16 32x32 48x48" href="/assets/images/favicon.ico" type="image/x-icon">
> However, according to the [GOV.UK_Frontend v](https://github.com/alphagov/govuk-frontend/releases/tag/v4.8.0) 4.8.0 repo, only one 16x16 favicon is provided.

Where is 16x16 coming from? The `favicon.ico` that is included in this PR (and the assets provided by GDS) is `48x48`. An `ico` is not a scalable format. GOV.UK provide an SVG as a scalable `favicon.ico`. For this PR, that isn't necessary.  

<img width="387" alt="image" src="https://github.com/dvsa/olcs-maintenance-page/assets/638172/b50cfb78-d2d6-4d3e-b9fb-ef386149abb2">

Straight from the GDS docs ⬆️ The line below shows how to provide a scalable favicon in SVG - but again, for this page, not necessary.

Documentation: https://design-system.service.gov.uk/styles/page-template/

> To maintain consistency across our projects, what do you think about updating the favicon across all repositories to match the guidelines provided by GOV.UK_Frontend v4.8.0 or just remove on this repo?

It'll be something that is refactored in the future. There's no direct link between this page and the application itself.

2024-02-20 15:07 UTC, sanakhandvsa commented on index.html
> +    <link rel="shortcut icon" sizes="16x16 32x32 48x48" href="/assets/images/favicon.ico" type="image/x-icon">
Thanks changed to 48x48.

2024-02-20 15:18 UTC, merged